name: CREBS Monitor
on:
  schedule:
    - cron: '*/30 * * * *' # Every 30 mins
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - setup-python: '3.10'
      - run: pip install -r requirements.txt
      - name: Run Script
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python scraper.py
      - name: Save History
        run: |
          git config --global user.name 'Bot'
          git config --global user.email 'bot@bot.com'
          git add scrape_history.json
          git commit -m "Update history [skip ci]" || exit 0
          git push
